//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspGetMotherDetailsByMobileno_Result
    {
        public string Name { get; set; }
        public string Husbname { get; set; }
        public string UnitCode { get; set; }
        public string UnitNameHindi { get; set; }
        public string VillageNameHindi { get; set; }
        public string pctsid { get; set; }
        public int MotherID { get; set; }
        public string Mobileno { get; set; }
        public string DistrictName { get; set; }
        public int totinf { get; set; }
        public Nullable<int> infantid { get; set; }
        public string TokenNo { get; set; }
    }
}
