//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspInfantDetailsByInfantID_Result
    {
        public string ChildName { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birth_date { get; set; }
        public Nullable<double> Weight { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string ReasonName { get; set; }
        public string immuname { get; set; }
        public Nullable<System.DateTime> immudate { get; set; }
        public string tagname { get; set; }
    }
}
