//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspANMusageDetailsDayWise_Result
    {
        public string unitname { get; set; }
        public string anmname { get; set; }
        public string unitcode { get; set; }
        public int ancCount { get; set; }
        public int pncCount { get; set; }
        public int immuCount { get; set; }
        public int maternalDeathount { get; set; }
        public int infantDeathount { get; set; }
        public string Phone { get; set; }
        public string phcchcname { get; set; }
    }
}
