//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspGetAshaDetails_Result
    {
        public string AshaName { get; set; }
        public int unitid { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string DistrictName { get; set; }
        public string BlockName { get; set; }
        public string PCHCHCName { get; set; }
        public string PCHCHCAbbr { get; set; }
        public string UnitAbbr { get; set; }
        public short UnitType { get; set; }
        public int ANMAutoID { get; set; }
        public string Anganwariname { get; set; }
        public string AshaRole { get; set; }
    }
}
