//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspCheckPCTSIDByTagName_Result
    {
        public Nullable<int> DelplaceCode { get; set; }
        public Nullable<System.DateTime> DischargeDT { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Freeze { get; set; }
        public byte Media { get; set; }
    }
}
