//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspANMPerformanceApp_Result
    {
        public Nullable<int> DistrictWiseRCHRank { get; set; }
        public Nullable<int> BlockWiseRCHRank { get; set; }
        public Nullable<int> DistrictWiseRank_ANC3 { get; set; }
        public Nullable<int> DistrictWiseRank_InstDel { get; set; }
        public Nullable<int> DistrictWiseRank_FullImmu { get; set; }
        public Nullable<int> DistrictWiseRank_IUD { get; set; }
        public Nullable<int> DistrictWiseRank_Ster { get; set; }
        public Nullable<int> BlockWiseRank_ANC3 { get; set; }
        public Nullable<int> BlockWiseRank_InstDel { get; set; }
        public Nullable<int> BlockWiseRank_FullImmu { get; set; }
        public Nullable<int> BlockWiseRank_IUD { get; set; }
        public Nullable<int> BlockWiseRank_Ster { get; set; }
        public Nullable<int> DistrictWise_TotalUnit { get; set; }
        public Nullable<int> BlockWiseRank_TotalUnit { get; set; }
        public int StateWiseTotalUnit { get; set; }
        public int StateWiseRCHRank { get; set; }
        public int StateWiseRank_ANC3 { get; set; }
        public int StateWiseRank_InstDel { get; set; }
        public int StateWiseRank_FullImmu { get; set; }
        public int StateWiseRank_IUD { get; set; }
        public int StateWiseRank_Ster { get; set; }
        public int StateWiseEmoji { get; set; }
        public int DistrictWiseEmoji { get; set; }
        public int BlockWiseEmoji { get; set; }
    }
}
