//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class USPDeathListForInfant_Result
    {
        public string mothername { get; set; }
        public string Husbname { get; set; }
        public byte Age { get; set; }
        public string pctsid { get; set; }
        public int MotherID { get; set; }
        public System.DateTime DeathDate { get; set; }
        public string ReasonName { get; set; }
        public string DeathReport { get; set; }
        public string deathPlaces { get; set; }
        public Nullable<byte> deathPlace { get; set; }
        public string ChildName { get; set; }
        public System.DateTime Birth_date { get; set; }
        public int InfantID { get; set; }
        public string childid { get; set; }
        public string Sex { get; set; }
    }
}
