//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANCRegDetail_Offline
    {
        public int ANCRegID { get; set; }
        public int MotherID { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime LMPDT { get; set; }
        public byte DelFlag { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int ashaAutoID { get; set; }
        public byte HighRisk { get; set; }
        public byte Freeze_AadhaarBankInfo { get; set; }
        public int VillageAutoID { get; set; }
        public byte BPL { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
