//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASHA_AddlCharge
    {
        public int AshaAutoID { get; set; }
        public int AnganwariNo { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public int AdditionalChargeID { get; set; }
        public byte MainAnganwari { get; set; }
    }
}
