//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASHADetail
    {
        public int ashaAutoID { get; set; }
        public Nullable<int> AnganwariNo { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public byte IsFather { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public Nullable<byte> ChildrenNo { get; set; }
        public Nullable<byte> EduQualification { get; set; }
        public string ProfessionalDegree { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<byte> LevelofTraining { get; set; }
        public string FatherHusbandName { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<byte> IsExtend { get; set; }
    }
}
