//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AshaMaster
    {
        public string unitcode { get; set; }
        public string AshaName { get; set; }
        public string AshaPhone { get; set; }
        public string IsDeleted { get; set; }
        public string Villagename { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> VillageAutoID { get; set; }
        public Nullable<System.DateTime> EIDTime { get; set; }
        public string Aadhaar_EID { get; set; }
        public string rename_AadhaarNo { get; set; }
        public string Ifsc_code { get; set; }
        public string Accountno { get; set; }
        public string Accounttype { get; set; }
        public string Bankname { get; set; }
        public Nullable<int> unitid { get; set; }
        public int ashaAutoID { get; set; }
        public Nullable<byte> ANM_AddlChargeFlag { get; set; }
        public byte Status { get; set; }
        public Nullable<byte> VerifiedAccount { get; set; }
        public byte VerifiedAccountByBank { get; set; }
        public string rename_bhamashahid { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public string CUGMobile { get; set; }
        public string RationCardNo { get; set; }
        public byte VerifyMobileNo { get; set; }
        public Nullable<byte> IFMSMapped { get; set; }
        public Nullable<byte> ANMType { get; set; }
        public Nullable<byte> WorkingAtLocation { get; set; }
        public string AccountVerificationBy { get; set; }
        public Nullable<byte> AccountVerifierRoleType { get; set; }
        public Nullable<System.DateTime> AccountVerificationDate { get; set; }
    }
}
