//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathDetail
    {
        public int DeathID { get; set; }
        public int motherid { get; set; }
        public int infantid { get; set; }
        public string Name { get; set; }
        public byte ReasonID { get; set; }
        public byte Age { get; set; }
        public System.DateTime DeathDate { get; set; }
        public Nullable<byte> deathPlace { get; set; }
        public int VillageAutoID { get; set; }
        public byte AgeType { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<byte> Bfeed { get; set; }
        public Nullable<byte> BloodGroup { get; set; }
        public Nullable<byte> IsImmun { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> DeathReportDate { get; set; }
        public string MasterMobile { get; set; }
        public string Relative_Name { get; set; }
        public int ashaautoid { get; set; }
        public int DeathUnitID { get; set; }
        public int EntryUnitID { get; set; }
        public byte Media { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public Nullable<byte> Preventable { get; set; }
        public byte ANMVerify { get; set; }
        public Nullable<System.DateTime> ANMVerificationDate { get; set; }
    }
}
