//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationMaster
    {
        public int DesigID { get; set; }
        public string DesigName { get; set; }
        public Nullable<byte> IsValidtoPhysVerification { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateIP { get; set; }
    }
}
