//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DHSMasterCode
    {
        public int ParentID { get; set; }
        public int masterID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Description { get; set; }
        public Nullable<byte> gender { get; set; }
    }
}
