//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HBPNC
    {
        public int Motherid { get; set; }
        public int Ancregid { get; set; }
        public byte PNCFlag { get; set; }
        public Nullable<byte> PNCComp { get; set; }
        public Nullable<byte> PPCM { get; set; }
        public Nullable<int> unitid1 { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<System.DateTime> PNCDate { get; set; }
        public Nullable<int> Ashaautoid { get; set; }
        public Nullable<int> ReferUnitID { get; set; }
        public Nullable<int> Child1_InfantID { get; set; }
        public Nullable<double> Child1_Weight { get; set; }
        public Nullable<int> Child2_InfantID { get; set; }
        public Nullable<byte> Child2_Comp { get; set; }
        public Nullable<double> Child2_Weight { get; set; }
        public Nullable<int> Child3_InfantID { get; set; }
        public Nullable<byte> Child3_Comp { get; set; }
        public Nullable<double> Child3_Weight { get; set; }
        public Nullable<int> Child4_InfantID { get; set; }
        public Nullable<byte> Child4_Comp { get; set; }
        public Nullable<double> Child4_Weight { get; set; }
        public Nullable<int> Child5_InfantID { get; set; }
        public Nullable<byte> Child5_Comp { get; set; }
        public Nullable<double> Child5_Weight { get; set; }
        public Nullable<byte> Child1_Comp { get; set; }
        public int Freeze { get; set; }
        public int S_mthyr { get; set; }
        public int VillageAutoID { get; set; }
        public int ANMautoid { get; set; }
        public Nullable<byte> Child1_IsLive { get; set; }
        public Nullable<byte> Child2_IsLive { get; set; }
        public Nullable<byte> Child3_IsLive { get; set; }
        public Nullable<byte> Child4_IsLive { get; set; }
        public Nullable<byte> Child5_IsLive { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte Media { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string EntryBy { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public byte ANMVerify { get; set; }
        public Nullable<System.DateTime> ANMVerificationDate { get; set; }
        public Nullable<byte> MotherChildHealthFlag { get; set; }
        public Nullable<byte> MotherCondition { get; set; }
        public Nullable<byte> Child1_Condition { get; set; }
        public Nullable<byte> Child2_Condition { get; set; }
        public Nullable<byte> Child3_Condition { get; set; }
        public Nullable<byte> Child4_Condition { get; set; }
        public Nullable<byte> Child5_Condition { get; set; }
        public Nullable<double> Child1_Temperature { get; set; }
        public Nullable<double> Child2_Temperature { get; set; }
        public Nullable<double> Child3_Temperature { get; set; }
        public Nullable<double> Child4_Temperature { get; set; }
        public Nullable<double> Child5_Temperature { get; set; }
        public Nullable<byte> Child1_Breath { get; set; }
        public Nullable<byte> Child2_Breath { get; set; }
        public Nullable<byte> Child3_Breath { get; set; }
        public Nullable<byte> Child4_Breath { get; set; }
        public Nullable<byte> Child5_Breath { get; set; }
        public Nullable<byte> Child1_KMC { get; set; }
        public Nullable<byte> Child2_KMC { get; set; }
        public Nullable<byte> Child3_KMC { get; set; }
        public Nullable<byte> Child4_KMC { get; set; }
        public Nullable<byte> Child5_KMC { get; set; }
        public Nullable<int> Child1_ReferUnitID { get; set; }
        public Nullable<int> Child2_ReferUnitID { get; set; }
        public Nullable<int> Child3_ReferUnitID { get; set; }
        public Nullable<int> Child4_ReferUnitID { get; set; }
        public Nullable<int> Child5_ReferUnitID { get; set; }
        public Nullable<byte> Child1_TreatMent { get; set; }
        public Nullable<byte> Child2_TreatMent { get; set; }
        public Nullable<byte> Child3_TreatMent { get; set; }
        public Nullable<byte> Child4_TreatMent { get; set; }
        public Nullable<byte> Child5_TreatMent { get; set; }
        public Nullable<byte> Child1_ReferTreatMent { get; set; }
        public Nullable<byte> Child2_ReferTreatMent { get; set; }
        public Nullable<byte> Child3_ReferTreatMent { get; set; }
        public Nullable<byte> Child4_ReferTreatMent { get; set; }
        public Nullable<byte> Child5_ReferTreatMent { get; set; }
        public Nullable<int> S_mthyr_HBPNC { get; set; }
        public Nullable<int> Freeze_HBPNC { get; set; }
    }
}
