//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighRiskCas
    {
        public int ANCRegid { get; set; }
        public byte ANCFlag { get; set; }
        public int Ashaautoid { get; set; }
        public System.DateTime ANCDate { get; set; }
        public Nullable<int> unitid1 { get; set; }
        public string DoctorName1 { get; set; }
        public Nullable<int> anganwariNo1 { get; set; }
        public int motherid { get; set; }
        public int VillageAutoID { get; set; }
        public int DelPlaceUnitID { get; set; }
        public int ContactUnitID { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public byte Media { get; set; }
        public byte ANMVerify { get; set; }
        public Nullable<System.DateTime> ANMVerificationDate { get; set; }
        public Nullable<int> S_mthyr { get; set; }
        public Nullable<int> Freeze { get; set; }
    }
}
