//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immunization_Offline
    {
        public int InfantID { get; set; }
        public System.DateTime immudate { get; set; }
        public byte ImmuCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int ashaAutoID { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte Media { get; set; }
        public int EntryUnitID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
    }
}
