//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImmunizationMaster_Offline
    {
        public byte ImmuCode { get; set; }
        public string ImmuName { get; set; }
        public string ImmuNameH { get; set; }
        public Nullable<int> duedays { get; set; }
        public Nullable<int> MaxDays { get; set; }
        public string DistrictCode { get; set; }
    }
}
