//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infant
    {
        public int MotherID { get; set; }
        public byte ID { get; set; }
        public int InfantID { get; set; }
        public string ChildName { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<byte> Bfeed { get; set; }
        public Nullable<byte> BloodGroup { get; set; }
        public System.DateTime Birth_date { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int ANCRegID { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<byte> VikrtiCode { get; set; }
        public Nullable<byte> NBCC_NBSU { get; set; }
        public byte Isdeleted { get; set; }
        public byte Status { get; set; }
        public byte Media { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public Nullable<byte> BabyKit { get; set; }
        public string RCHID { get; set; }
        public string ChildNameH { get; set; }
        public string ChildNameE { get; set; }
    }
}
