//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaaToken
    {
        public string Mobileno { get; set; }
        public string DeviceID { get; set; }
        public string Salt { get; set; }
        public System.DateTime Date { get; set; }
    }
}
