//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail
    {
        public int SurveyYear { get; set; }
        public int UnitID { get; set; }
        public int AnganwariNo { get; set; }
        public int HouseFamilyID { get; set; }
        public string Name { get; set; }
        public byte Age { get; set; }
        public byte Sex { get; set; }
        public string MobileNo { get; set; }
        public string AadhaarNo { get; set; }
        public byte Profession { get; set; }
        public byte RelationToHead { get; set; }
        public string PollutionHazards { get; set; }
        public byte MaritalStatus { get; set; }
        public int MemberID { get; set; }
        public byte Education { get; set; }
        public Nullable<byte> MobileNoBelongsToWhom { get; set; }
        public System.DateTime Entrydate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int EntryByUserNo { get; set; }
        public int UpdateByUserNo { get; set; }
        public string RationCardNo { get; set; }
        public string DiseasesCodes { get; set; }
        public Nullable<int> SpouseID { get; set; }
        public Nullable<System.DateTime> Entrydate_online { get; set; }
        public Nullable<System.DateTime> LastUpdateDate_online { get; set; }
        public Nullable<int> Fatherid { get; set; }
        public Nullable<int> Motherid { get; set; }
    }
}
