//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mother_App
    {
        public int Mother_AppID { get; set; }
        public int VillageAutoID { get; set; }
        public string Name { get; set; }
        public string Husbname { get; set; }
        public byte Age { get; set; }
        public Nullable<int> Height { get; set; }
        public string Address { get; set; }
        public byte Cast { get; set; }
        public Nullable<byte> CastGroup { get; set; }
        public string ECID { get; set; }
        public byte LiveChild { get; set; }
        public string Mobileno { get; set; }
        public string Ifsc_code { get; set; }
        public string Accountno { get; set; }
        public string RationCardNo { get; set; }
        public string AccountName { get; set; }
        public byte IsHusband { get; set; }
        public string BHAMASHAHID { get; set; }
        public string AadhaarNo { get; set; }
        public string JanAadhaarNo { get; set; }
        public string PCTSID { get; set; }
        public int MotherID { get; set; }
        public byte Consent { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime LMPDT { get; set; }
        public int ashaAutoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int EntryUnitVillage { get; set; }
        public Nullable<byte> Location_Rajasthan { get; set; }
        public Nullable<byte> DirectDelivery { get; set; }
        public Nullable<byte> Ghamantu { get; set; }
        public byte NFSA { get; set; }
        public byte BPL { get; set; }
        public string BPLCardNo { get; set; }
        public byte BeforeDelivery500 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte Media { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public string ErrorMsg { get; set; }
        public int ANCRegID { get; set; }
    }
}
