//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class rajmedicalEntities : DbContext
    {
        public rajmedicalEntities()
            : base("name=rajmedicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anganwari_Village> Anganwari_Village { get; set; }
        public DbSet<AnganwariMaster> AnganwariMasters { get; set; }
        public DbSet<ASHA_AddlCharge> ASHA_AddlCharge { get; set; }
        public DbSet<ASHADetail> ASHADetails { get; set; }
        public DbSet<AshaMaster> AshaMasters { get; set; }
        public DbSet<MasterCodes> MasterCodes { get; set; }
        public DbSet<HistorySwasthyaMitrk> HistorySwasthyaMitrks { get; set; }
        public DbSet<SwasthyaMitrk> SwasthyaMitrks { get; set; }
        public DbSet<DesignationMaster> DesignationMasters { get; set; }
        public DbSet<UnitTypeMaster> UnitTypeMasters { get; set; }
        public DbSet<UnitMaster> UnitMasters { get; set; }
        public DbSet<Village> Villages { get; set; }
        public DbSet<HealthUnitPhoto> HealthUnitPhotoes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<AppHistory> AppHistories { get; set; }
    
        public virtual ObjectResult<GetANMForLinelist_Result> GetANMForLinelist(Nullable<int> ashaautoid)
        {
            var ashaautoidParameter = ashaautoid.HasValue ?
                new ObjectParameter("ashaautoid", ashaautoid) :
                new ObjectParameter("ashaautoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetANMForLinelist_Result>("GetANMForLinelist", ashaautoidParameter);
        }
    
        public virtual ObjectResult<uspGetUnitName_Result> uspGetUnitName(string distcode)
        {
            var distcodeParameter = distcode != null ?
                new ObjectParameter("distcode", distcode) :
                new ObjectParameter("distcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetUnitName_Result>("uspGetUnitName", distcodeParameter);
        }
    
        public virtual ObjectResult<uspGetanganwari_Result> uspGetanganwari(Nullable<int> ashaautoid)
        {
            var ashaautoidParameter = ashaautoid.HasValue ?
                new ObjectParameter("ashaautoid", ashaautoid) :
                new ObjectParameter("ashaautoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetanganwari_Result>("uspGetanganwari", ashaautoidParameter);
        }
    
        public virtual ObjectResult<GetASHAForLinelist_Result> GetASHAForLinelist(Nullable<int> perm_unitid, Nullable<int> perm_villageautoid, Nullable<int> perm_deliveryplaceunitid, string perm_LoginUnitcode)
        {
            var perm_unitidParameter = perm_unitid.HasValue ?
                new ObjectParameter("Perm_unitid", perm_unitid) :
                new ObjectParameter("Perm_unitid", typeof(int));
    
            var perm_villageautoidParameter = perm_villageautoid.HasValue ?
                new ObjectParameter("Perm_villageautoid", perm_villageautoid) :
                new ObjectParameter("Perm_villageautoid", typeof(int));
    
            var perm_deliveryplaceunitidParameter = perm_deliveryplaceunitid.HasValue ?
                new ObjectParameter("Perm_deliveryplaceunitid", perm_deliveryplaceunitid) :
                new ObjectParameter("Perm_deliveryplaceunitid", typeof(int));
    
            var perm_LoginUnitcodeParameter = perm_LoginUnitcode != null ?
                new ObjectParameter("Perm_LoginUnitcode", perm_LoginUnitcode) :
                new ObjectParameter("Perm_LoginUnitcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetASHAForLinelist_Result>("GetASHAForLinelist", perm_unitidParameter, perm_villageautoidParameter, perm_deliveryplaceunitidParameter, perm_LoginUnitcodeParameter);
        }
    
        public virtual ObjectResult<uspSwasthyaMitrkLocation_Result> uspSwasthyaMitrkLocation(Nullable<int> perm_anmautoid)
        {
            var perm_anmautoidParameter = perm_anmautoid.HasValue ?
                new ObjectParameter("Perm_anmautoid", perm_anmautoid) :
                new ObjectParameter("Perm_anmautoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspSwasthyaMitrkLocation_Result>("uspSwasthyaMitrkLocation", perm_anmautoidParameter);
        }
    
        public virtual ObjectResult<uspSwasthyaMitrkData_Result> uspSwasthyaMitrkData(Nullable<int> perm_unitid)
        {
            var perm_unitidParameter = perm_unitid.HasValue ?
                new ObjectParameter("Perm_unitid", perm_unitid) :
                new ObjectParameter("Perm_unitid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspSwasthyaMitrkData_Result>("uspSwasthyaMitrkData", perm_unitidParameter);
        }
    
        public virtual ObjectResult<uspGetANMForOtherUser_Result> uspGetANMForOtherUser(string perm_unitcode)
        {
            var perm_unitcodeParameter = perm_unitcode != null ?
                new ObjectParameter("Perm_unitcode", perm_unitcode) :
                new ObjectParameter("Perm_unitcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetANMForOtherUser_Result>("uspGetANMForOtherUser", perm_unitcodeParameter);
        }
    
        public virtual ObjectResult<uspGetANMForOtherUserNew_Result> uspGetANMForOtherUserNew(string perm_unitcode)
        {
            var perm_unitcodeParameter = perm_unitcode != null ?
                new ObjectParameter("Perm_unitcode", perm_unitcode) :
                new ObjectParameter("Perm_unitcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetANMForOtherUserNew_Result>("uspGetANMForOtherUserNew", perm_unitcodeParameter);
        }
    
        public virtual ObjectResult<uspGetAshaDetails_Result> uspGetAshaDetails(Nullable<int> perm_anmautoid)
        {
            var perm_anmautoidParameter = perm_anmautoid.HasValue ?
                new ObjectParameter("Perm_anmautoid", perm_anmautoid) :
                new ObjectParameter("Perm_anmautoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAshaDetails_Result>("uspGetAshaDetails", perm_anmautoidParameter);
        }
    
        public virtual ObjectResult<uspGetANMForOtherUserNewDemo_Result> uspGetANMForOtherUserNewDemo(string perm_unitcode, Nullable<byte> ashaType)
        {
            var perm_unitcodeParameter = perm_unitcode != null ?
                new ObjectParameter("Perm_unitcode", perm_unitcode) :
                new ObjectParameter("Perm_unitcode", typeof(string));
    
            var ashaTypeParameter = ashaType.HasValue ?
                new ObjectParameter("AshaType", ashaType) :
                new ObjectParameter("AshaType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetANMForOtherUserNewDemo_Result>("uspGetANMForOtherUserNewDemo", perm_unitcodeParameter, ashaTypeParameter);
        }
    
        public virtual ObjectResult<UspHealthunitphoto_Result> UspHealthunitphoto(Nullable<int> unitid)
        {
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspHealthunitphoto_Result>("UspHealthunitphoto", unitidParameter);
        }
    
        public virtual ObjectResult<uspGetVillageByAshaID_Result> uspGetVillageByAshaID(Nullable<int> ashaautoid)
        {
            var ashaautoidParameter = ashaautoid.HasValue ?
                new ObjectParameter("ashaautoid", ashaautoid) :
                new ObjectParameter("ashaautoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetVillageByAshaID_Result>("uspGetVillageByAshaID", ashaautoidParameter);
        }
    
        public virtual ObjectResult<uspGetANMDetails_Result> uspGetANMDetails(Nullable<int> perm_anmautoid, Nullable<byte> permType)
        {
            var perm_anmautoidParameter = perm_anmautoid.HasValue ?
                new ObjectParameter("Perm_anmautoid", perm_anmautoid) :
                new ObjectParameter("Perm_anmautoid", typeof(int));
    
            var permTypeParameter = permType.HasValue ?
                new ObjectParameter("PermType", permType) :
                new ObjectParameter("PermType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetANMDetails_Result>("uspGetANMDetails", perm_anmautoidParameter, permTypeParameter);
        }
    }
}
