//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Log
    {
        public int SNo { get; set; }
        public string Unitcode { get; set; }
        public string UserID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<byte> MsgType { get; set; }
        public string ReceiverUnitcode { get; set; }
        public Nullable<int> MthYr { get; set; }
        public Nullable<int> smsCount { get; set; }
        public string MessageText { get; set; }
    }
}
