//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrailLog
    {
        public int Sno { get; set; }
        public string MobileNo { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> ApiCode { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
    }
}
