//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villages_Offline
    {
        public string UnitCode { get; set; }
        public string VillageName { get; set; }
        public string UnitNameHindi { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<int> unitid { get; set; }
        public int VillageAutoID { get; set; }
        public byte OtherLocation { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
