//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspRecordVerificationImmunization_Result
    {
        public int InfantID { get; set; }
        public string VillageName { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
        public string Block { get; set; }
        public string CHCPHC { get; set; }
        public string district { get; set; }
        public string mothername { get; set; }
        public string pctsid { get; set; }
        public string Husbname { get; set; }
        public string ChildName { get; set; }
        public System.DateTime Birth_date { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<byte> Sex { get; set; }
        public int ANCRegID { get; set; }
        public int MotherID { get; set; }
        public string childid { get; set; }
    }
}
