//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public string UnitCode { get; set; }
        public Nullable<int> VillageID { get; set; }
        public string VillageName { get; set; }
        public string CensusCode { get; set; }
        public string ACCode { get; set; }
        public string PCCode { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UnitNameHindi { get; set; }
        public string Pop_male { get; set; }
        public string Pop_female { get; set; }
        public string Pop_SC { get; set; }
        public string Pop_ST { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string pincode { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<int> unitid { get; set; }
        public int VillageAutoID { get; set; }
        public byte OtherLocation { get; set; }
        public string CensusCode2011 { get; set; }
        public Nullable<int> VillageLgCode { get; set; }
        public Nullable<int> SVID { get; set; }
        public int RCHVcode { get; set; }
        public Nullable<byte> IsRevenue { get; set; }
        public Nullable<int> Pop_transgender { get; set; }
        public byte IsDeleted { get; set; }
    }
}
