//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppHistory
    {
        public string VersionName { get; set; }
        public System.DateTime RealeaseDate { get; set; }
        public string BugFixes { get; set; }
        public string NewAddition { get; set; }
        public byte AppFlag { get; set; }
        public int VersionID { get; set; }
        public int LiveFlag { get; set; }
    }
}
