//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspPNClist_Result
    {
        public string pctsid { get; set; }
        public int MotherID { get; set; }
        public string Name { get; set; }
        public string Husbname { get; set; }
        public string Address { get; set; }
        public int ANCRegID { get; set; }
        public Nullable<System.DateTime> Prasav_date { get; set; }
        public string PNCDueDate { get; set; }
    }
}
