//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainSuggestion
    {
        public int ComplainID { get; set; }
        public int motherid { get; set; }
        public System.DateTime ComplainSuggestionDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Description { get; set; }
        public string ReplyMessage { get; set; }
        public Nullable<int> Userno { get; set; }
        public Nullable<System.DateTime> Replydate { get; set; }
        public string IPAddress { get; set; }
    }
}
