//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class USPAshasoftClick_Result
    {
        public string AcitivityNameHindi { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
