//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspLineListDeliveryDetails_Result
    {
        public Nullable<byte> FoodFlag { get; set; }
        public Nullable<byte> BloodFlag { get; set; }
        public Nullable<byte> ReferFrom { get; set; }
        public string AdmissionDate { get; set; }
        public Nullable<int> ReferFromUnitID { get; set; }
        public Nullable<byte> ReferAfterAdmission { get; set; }
        public string referFromUnitcode { get; set; }
        public Nullable<byte> ReferAfterAdmissionCode { get; set; }
        public int FinYear { get; set; }
        public Nullable<byte> fooddays { get; set; }
        public Nullable<byte> bloodunit { get; set; }
        public byte NFSA { get; set; }
        public int EntryUnitID { get; set; }
        public short Regunittype { get; set; }
        public byte deliveryplaceunittype { get; set; }
        public string deliveryplaceunitcode { get; set; }
        public byte LiveChild { get; set; }
        public byte Location_Rajasthan { get; set; }
        public byte Ghamantu { get; set; }
        public byte DirectDelivery { get; set; }
        public byte BPL { get; set; }
        public byte ComplicationReasonM { get; set; }
        public byte ComplicationReasonI { get; set; }
        public int DischargeUnitID { get; set; }
        public int villageautoid { get; set; }
        public byte HighRisk { get; set; }
        public Nullable<int> Freeze { get; set; }
        public byte RuralUrban { get; set; }
        public string dischargeUnitcode { get; set; }
        public string CottageWard { get; set; }
        public byte InfantRefer { get; set; }
        public string PreviousDeliveryDate { get; set; }
        public byte outcome { get; set; }
        public int Freeze_IsPPS { get; set; }
        public int Freeze_3YearSpacing { get; set; }
        public Nullable<byte> IsppsNppiucd { get; set; }
        public int Freeze_Inst { get; set; }
        public int Freeze_IsppsNppiucd { get; set; }
        public int anganwariNo { get; set; }
        public int ashaAutoID { get; set; }
        public int motherid { get; set; }
        public string pctsid { get; set; }
        public int ancregid { get; set; }
        public string Name { get; set; }
        public string villagename { get; set; }
        public string unitcode { get; set; }
        public string Husbname { get; set; }
        public string Mobileno { get; set; }
        public byte age { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime lmpdt { get; set; }
        public int DelplaceCode { get; set; }
        public Nullable<byte> Deltype { get; set; }
        public byte Complication { get; set; }
        public string Prasav_date { get; set; }
        public string DischargeDT { get; set; }
        public string ANCDate { get; set; }
        public byte ojasUnittype { get; set; }
        public Nullable<byte> pncflag { get; set; }
        public string wedate { get; set; }
        public Nullable<byte> birthOrder { get; set; }
        public int RegUnitid { get; set; }
        public int delplace { get; set; }
    }
}
