//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDataforManageHBYCList_Result
    {
        public Nullable<double> Weight { get; set; }
        public byte BloodGroup { get; set; }
        public string ChildName { get; set; }
        public byte Sex { get; set; }
        public System.DateTime Birth_date { get; set; }
        public int finyear { get; set; }
        public int villageautoid { get; set; }
        public string unitcode { get; set; }
        public string villagename { get; set; }
        public string childid { get; set; }
        public int ancregid { get; set; }
        public int motherid { get; set; }
        public string pctsid { get; set; }
        public string name { get; set; }
        public string Mobileno { get; set; }
        public byte age { get; set; }
        public string Husbname { get; set; }
        public string ECID { get; set; }
        public byte IsHusband { get; set; }
        public Nullable<int> ReferUnitID { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> HBYCWeight { get; set; }
        public byte HBYCFlag { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<byte> ORSPacket { get; set; }
        public Nullable<byte> IFASirap { get; set; }
        public Nullable<byte> GrowthChart { get; set; }
        public Nullable<byte> Color { get; set; }
        public Nullable<byte> FoodAccordingAge { get; set; }
        public Nullable<byte> GrowthLate { get; set; }
        public Nullable<byte> Refer { get; set; }
        public int ashaAutoID { get; set; }
        public int RegUnitid { get; set; }
        public short RegUnittype { get; set; }
        public int infantid { get; set; }
        public string ReferUnitcode { get; set; }
        public Nullable<short> ReferUnittype { get; set; }
        public Nullable<byte> ANMVerify { get; set; }
        public Nullable<byte> Media { get; set; }
        public Nullable<int> Freeze { get; set; }
    }
}
