//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspMaaAdvanceSearch_Result
    {
        public int ANCRegID { get; set; }
        public string Schemefalg { get; set; }
        public byte InstallmentNo { get; set; }
        public byte PaymentMode { get; set; }
        public string AccountNo { get; set; }
        public int InfantID { get; set; }
        public int Amount { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<int> ChequeAmount { get; set; }
        public string Bank_Name { get; set; }
        public string IFSC_CODE { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
    }
}
