//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaaVideoDetail
    {
        public int ID { get; set; }
        public short VideoType { get; set; }
        public string Descrption { get; set; }
        public string VideoName { get; set; }
        public string Extension { get; set; }
        public System.DateTime UploadeDate { get; set; }
        public string ImageName { get; set; }
    }
}
