//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspUserAuthenticate_Result
    {
        public string UnitCode { get; set; }
        public Nullable<int> unitid { get; set; }
        public string ANMName { get; set; }
        public System.DateTime Saltcreatedon { get; set; }
        public string Saltvalue { get; set; }
        public string Password { get; set; }
        public string UnitName { get; set; }
        public byte resetpwd { get; set; }
        public short UnitType { get; set; }
        public int ANMAutoID { get; set; }
        public byte AppRoleID { get; set; }
        public string UserContactNo { get; set; }
        public int UserNo { get; set; }
        public string DistrictName { get; set; }
        public string BlockName { get; set; }
        public string PCHCHCName { get; set; }
        public string PCHCHCAbbr { get; set; }
        public string UnitAbbr { get; set; }
        public int IsExp { get; set; }
        public Nullable<System.DateTime> TrailTime { get; set; }
        public short Trail { get; set; }
        public int EligibleForSurvey { get; set; }
        public string AnganwariEnglish { get; set; }
        public string AnganwariHindi { get; set; }
        public string VillageName { get; set; }
        public string ClaimANMName { get; set; }
        public string ClaimANMPhone { get; set; }
        public string AdminPassword { get; set; }
    }
}
