//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherStatu
    {
        public int motherid { get; set; }
        public byte reasonid { get; set; }
        public string UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public int motherid_R { get; set; }
        public int Villageautoid_R { get; set; }
        public int LiveChild_R { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
