//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspGetANCData_Result
    {
        public int Mother_MotherID { get; set; }
        public string Mother_ECID { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_Address { get; set; }
        public byte Mother_Age { get; set; }
        public byte Mother_Cast { get; set; }
        public byte Mother_LiveChild { get; set; }
        public string Mother_Mobileno { get; set; }
        public string Mother_Husbname { get; set; }
        public string Mother_pctsid { get; set; }
        public int Mother_ancregid { get; set; }
        public byte Mother_IsHusband { get; set; }
        public Nullable<int> Mother_Height { get; set; }
        public byte Mother_Status { get; set; }
        public int ANCRegDetail_ANCRegID { get; set; }
        public int ANCRegDetail_MotherID { get; set; }
        public System.DateTime ANCRegDetail_RegDate { get; set; }
        public System.DateTime ANCRegDetail_LMPDT { get; set; }
        public byte ANCRegDetail_DelFlag { get; set; }
        public Nullable<System.DateTime> ANCRegDetail_EntryDate { get; set; }
        public int ANCRegDetail_ashaAutoID { get; set; }
        public byte ANCRegDetail_HighRisk { get; set; }
        public byte ANCRegDetail_Freeze_AadhaarBankInfo { get; set; }
        public int ANCRegDetail_VillageAutoID { get; set; }
        public byte ANCRegDetail_bpl { get; set; }
        public Nullable<System.DateTime> ANCRegDetail_LastUpdated { get; set; }
        public Nullable<int> ANCRegID_1 { get; set; }
        public Nullable<byte> ANCFlag_1 { get; set; }
        public Nullable<System.DateTime> ANCDate_1 { get; set; }
        public Nullable<System.DateTime> TT1_1 { get; set; }
        public Nullable<System.DateTime> TT2_1 { get; set; }
        public Nullable<System.DateTime> TTB_1 { get; set; }
        public Nullable<System.DateTime> IFA_1 { get; set; }
        public Nullable<double> HB_1 { get; set; }
        public string CompL_1 { get; set; }
        public Nullable<byte> RTI_1 { get; set; }
        public int ashaAutoID_1 { get; set; }
        public Nullable<double> Weight_1 { get; set; }
        public Nullable<int> anganwariNo_1 { get; set; }
        public Nullable<int> motherid_1 { get; set; }
        public Nullable<int> ReferUnitID_1 { get; set; }
        public Nullable<int> VillageAutoID_1 { get; set; }
        public Nullable<int> BloodPressureS_1 { get; set; }
        public Nullable<int> BloodPressureD_1 { get; set; }
        public Nullable<byte> UrineA_1 { get; set; }
        public Nullable<byte> UrineS_1 { get; set; }
        public Nullable<int> TreatmentCode_1 { get; set; }
        public Nullable<System.DateTime> ALBE400_1 { get; set; }
        public Nullable<System.DateTime> CAL500_1 { get; set; }
        public Nullable<System.DateTime> Entrydate_1 { get; set; }
        public Nullable<byte> NormalLodingIronSucrose1_1 { get; set; }
        public Nullable<System.DateTime> IronSucrose1_1 { get; set; }
        public Nullable<System.DateTime> IronSucrose2_1 { get; set; }
        public Nullable<System.DateTime> IronSucrose3_1 { get; set; }
        public Nullable<System.DateTime> IronSucrose4_1 { get; set; }
        public Nullable<System.DateTime> LastUpdated_1 { get; set; }
        public Nullable<byte> Media_1 { get; set; }
        public string Latitude_1 { get; set; }
        public string Longitude_1 { get; set; }
        public Nullable<int> UpdateUserNo_1 { get; set; }
        public Nullable<int> EntryUserNo_1 { get; set; }
        public int Freeze_ANC3Checkup { get; set; }
    }
}
