//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspRecordvarificationReportsDetails_Result
    {
        public int ANCRegID { get; set; }
        public string officerName { get; set; }
        public string officerUserid { get; set; }
        public string officerContact { get; set; }
        public string CaseName { get; set; }
        public string Remarks { get; set; }
        public string MotherName { get; set; }
        public string HusbName { get; set; }
        public string pctsid { get; set; }
        public string VillageName { get; set; }
        public string UnitName { get; set; }
        public string PhcChc { get; set; }
        public string Block { get; set; }
        public string District { get; set; }
    }
}
