//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseFamily
    {
        public int SurveyYear { get; set; }
        public int UnitID { get; set; }
        public int AnganwariNo { get; set; }
        public int HouseNo { get; set; }
        public int FamiliyNo { get; set; }
        public int HouseFamilyID { get; set; }
        public byte Bpl { get; set; }
        public string BhamashahID { get; set; }
        public string Address { get; set; }
        public System.DateTime Entrydate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public byte Caste { get; set; }
        public byte Religion { get; set; }
        public byte Permanent_Residence { get; set; }
        public string FuelType { get; set; }
        public Nullable<System.DateTime> Entrydate_online { get; set; }
        public Nullable<System.DateTime> LastUpdateDate_online { get; set; }
    }
}
