//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspImmunizationSchedule_Result
    {
        public Nullable<int> infantid { get; set; }
        public string ChildName { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public Nullable<byte> ImmuCode { get; set; }
        public string ImmuName { get; set; }
        public string ImmuNameH { get; set; }
        public Nullable<System.DateTime> ImmuDate { get; set; }
    }
}
