//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspHighRisklist_Result
    {
        public int ancregid { get; set; }
        public string pctsid { get; set; }
        public int motherid { get; set; }
        public string villagename { get; set; }
        public int villageautoid { get; set; }
        public string name { get; set; }
        public string Husbname { get; set; }
        public byte age { get; set; }
        public string ecid { get; set; }
        public System.DateTime regdate { get; set; }
        public System.DateTime lmpdate { get; set; }
        public Nullable<byte> NotVerifiedAncFlag { get; set; }
    }
}
