//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDueListForANMVerification_Result
    {
        public int ashaAutoID { get; set; }
        public string AshaName { get; set; }
        public Nullable<int> TotalVerifiedCases { get; set; }
        public Nullable<int> TotalUnVerifiedCases { get; set; }
        public Nullable<int> TotalCases { get; set; }
    }
}
