//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildInformation
    {
        public int MemberID { get; set; }
        public Nullable<byte> Male { get; set; }
        public Nullable<byte> Female { get; set; }
        public Nullable<byte> Transgender { get; set; }
    }
}
