//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDashboardSerial_Result
    {
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public Nullable<byte> unittype { get; set; }
        public string BlockName { get; set; }
        public Nullable<int> Cases { get; set; }
        public Nullable<byte> clickable { get; set; }
    }
}
