//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwasthyaMitrk
    {
        public int SwasthyaMitrkID { get; set; }
        public int VillageAutoID { get; set; }
        public string Name { get; set; }
        public byte Sex { get; set; }
        public string MobileNo { get; set; }
        public string WhatsAppNo { get; set; }
        public Nullable<byte> Qualification { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> IsFather { get; set; }
        public string FatherHusbandName { get; set; }
        public string EmailID { get; set; }
        public Nullable<double> Experience { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public byte Status { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public byte Media { get; set; }
        public int EntryUserNo { get; set; }
        public int UpdateUserNo { get; set; }
    }
}
