//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetails_Offline
    {
        public int ANCRegID { get; set; }
        public int MotherID { get; set; }
        public System.DateTime Prasav_date { get; set; }
        public Nullable<System.DateTime> DischargeDT { get; set; }
        public Nullable<byte> Deltype { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> DelplaceCode { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
