//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnganwariMaster
    {
        public int AnganwariNo { get; set; }
        public Nullable<int> renameVillageAutoID { get; set; }
        public string NameE { get; set; }
        public string NameH { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte IsDeleted { get; set; }
        public string ICDSCode { get; set; }
        public string AWCID { get; set; }
        public string CensusCode { get; set; }
        public Nullable<byte> RuralUrban { get; set; }
        public int unitid { get; set; }
        public Nullable<int> ECCount { get; set; }
        public Nullable<int> Population2011 { get; set; }
        public Nullable<int> HouseHoldCount { get; set; }
        public Nullable<int> FamilyCount { get; set; }
        public Nullable<byte> MiniAnganwari { get; set; }
    }
}
