//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceToken
    {
        public string DeviceID { get; set; }
        public string TokenNo { get; set; }
        public string Saltvalue { get; set; }
        public System.DateTime Saltcreatedon { get; set; }
    }
}
