//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspCheckPCTSIDForDelivery_Result
    {
        public byte DelFlag { get; set; }
        public int Freeze_Inst { get; set; }
        public string freeze { get; set; }
        public string Unitcode { get; set; }
        public int RegUnitId { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public short Unittytpe { get; set; }
        public string Mobileno { get; set; }
        public Nullable<byte> Ghamantu { get; set; }
        public Nullable<byte> DirectDelivery { get; set; }
        public Nullable<byte> Location_Rajasthan { get; set; }
        public int AncRegID { get; set; }
        public Nullable<System.DateTime> delEntryDate { get; set; }
        public Nullable<byte> ojasUnittype { get; set; }
        public int MotherID { get; set; }
    }
}
