//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspANMAppDataCount_Result
    {
        public string DistrictName { get; set; }
        public string BlockName { get; set; }
        public string ChcPhcName { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<int> AshaAutoID { get; set; }
        public string AnmName { get; set; }
        public int CasesCount { get; set; }
    }
}
