//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnMarriedGirlsDetail
    {
        public int UnitID { get; set; }
        public int AnganwariNo { get; set; }
        public int MemberID { get; set; }
        public byte Flag { get; set; }
        public byte Duration { get; set; }
        public byte Used { get; set; }
        public string Cleaning { get; set; }
        public string TypeOfCleaningCloths { get; set; }
        public string FamiliyConcept { get; set; }
        public string PhysicalProblem { get; set; }
        public Nullable<byte> AdviceFrom { get; set; }
        public string DistroyNapkin { get; set; }
        public System.DateTime Entrydate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int SurveyYear { get; set; }
        public Nullable<System.DateTime> Entrydate_online { get; set; }
        public Nullable<System.DateTime> LastUpdateDate_online { get; set; }
    }
}
