//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspManageHighRiskCases_Result
    {
        public string Name { get; set; }
        public string HusbName { get; set; }
        public Nullable<byte> Age { get; set; }
        public string MobileNo { get; set; }
        public string VillageName { get; set; }
        public Nullable<int> VillageAutoID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> LmpDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> ANCDate { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public Nullable<byte> AncFlag { get; set; }
        public Nullable<int> Ashaautoid { get; set; }
        public string AshaName { get; set; }
        public Nullable<int> ContactUnitType { get; set; }
        public string ContactDistrictUnitCode { get; set; }
        public Nullable<int> ContactUnitID { get; set; }
        public Nullable<int> DelUnitType { get; set; }
        public string DelDistrictUnitCode { get; set; }
        public Nullable<int> DelPlaceUnitID { get; set; }
        public Nullable<int> ReferUnitType { get; set; }
        public string ReferDistrictUnitCode { get; set; }
        public Nullable<int> ReferUnitID { get; set; }
        public byte ANMVerify { get; set; }
        public Nullable<int> Freeze { get; set; }
        public Nullable<byte> Media { get; set; }
        public string ContactUnitName { get; set; }
        public string ECID { get; set; }
        public string ContactUnitCode { get; set; }
        public string DelUnitCode { get; set; }
    }
}
