//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDeliverylist_Result
    {
        public string pctsid { get; set; }
        public string Name { get; set; }
        public string Husbname { get; set; }
        public string Address { get; set; }
        public int ancregid { get; set; }
        public byte Age { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> expDeliveryDate { get; set; }
        public Nullable<System.DateTime> Prasav_date { get; set; }
        public byte DelFlag { get; set; }
        public int MotherID { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<int> RegUnitId { get; set; }
    }
}
