//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public string UnitCode { get; set; }
        public short UnitType { get; set; }
        public string UnitName { get; set; }
        public string ACcode { get; set; }
        public string PCcode { get; set; }
        public string CensusCode { get; set; }
        public string UnitIncharge { get; set; }
        public string UnitContactNo { get; set; }
        public string Remarks { get; set; }
        public string IsCHC { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string RuralUrban { get; set; }
        public string building { get; set; }
        public string UnitNameHindi { get; set; }
        public Nullable<short> BID { get; set; }
        public Nullable<short> PID { get; set; }
        public Nullable<short> SID { get; set; }
        public Nullable<short> PPUID { get; set; }
        public string mobileno { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string pincode { get; set; }
        public Nullable<byte> PrivateHospitalType11 { get; set; }
        public int UnitID { get; set; }
        public Nullable<byte> deliveryPoint { get; set; }
        public string AWCID { get; set; }
        public byte MTC { get; set; }
        public byte SNCU { get; set; }
        public int ReportingUnitID { get; set; }
        public Nullable<int> Beds { get; set; }
        public Nullable<int> BSBY { get; set; }
        public Nullable<int> AccreditationYear { get; set; }
        public int VillageAutoID_P { get; set; }
        public byte NUHMUrban { get; set; }
        public Nullable<byte> NBSU { get; set; }
        public Nullable<byte> NBCC { get; set; }
        public Nullable<byte> StaticsCenter { get; set; }
        public Nullable<byte> PHC_24Hour { get; set; }
        public Nullable<byte> FRU { get; set; }
        public string AppLatitude { get; set; }
        public string AppLongitude { get; set; }
        public Nullable<byte> WellnessCenter { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> BlockCode { get; set; }
        public Nullable<int> HmisID { get; set; }
        public Nullable<int> PehchanSubRegistrarCode { get; set; }
        public int TehsilID { get; set; }
        public byte IsDeleted { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string DDOCode { get; set; }
        public Nullable<System.DateTime> DDOCodeVerificationDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public byte TspArea { get; set; }
        public byte OfficeFlag { get; set; }
        public Nullable<int> Cemonc { get; set; }
        public Nullable<int> PSCode { get; set; }
        public Nullable<bool> IsMCH { get; set; }
        public Nullable<bool> IsTraumaCentre { get; set; }
        public Nullable<bool> IsBloodBank { get; set; }
        public Nullable<int> EstablishmentYear { get; set; }
        public Nullable<int> GPCode { get; set; }
        public Nullable<byte> CLMCFlag { get; set; }
        public Nullable<byte> IsRevenueBlock { get; set; }
        public Nullable<bool> IsBloodStorageUnit { get; set; }
        public Nullable<byte> RCHFacility { get; set; }
        public byte Funcational { get; set; }
        public byte HmisPrivateDataType { get; set; }
    }
}
