//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDashboard_Result
    {
        public Nullable<short> flag { get; set; }
        public int TotalANCReg { get; set; }
        public int ANCRegTrimaster { get; set; }
        public Nullable<int> DelPublic { get; set; }
        public Nullable<int> DelPrivate { get; set; }
        public Nullable<int> DelHome { get; set; }
        public Nullable<int> totalBirth { get; set; }
        public Nullable<int> LiveMale { get; set; }
        public Nullable<int> LiveFeMale { get; set; }
        public Nullable<int> StillBirth { get; set; }
        public Nullable<int> Abortion { get; set; }
        public Nullable<int> TotalChildrenReg { get; set; }
        public Nullable<int> FullyImmunized { get; set; }
        public Nullable<int> PartiallyImmunized { get; set; }
        public Nullable<int> NotImmunized { get; set; }
        public string Unitcode { get; set; }
        public string unitname { get; set; }
        public Nullable<byte> unittype { get; set; }
        public Nullable<double> percentage { get; set; }
        public string districtname { get; set; }
        public string blockname { get; set; }
        public Nullable<int> maxvalDist { get; set; }
        public Nullable<int> maxvalBlock { get; set; }
        public Nullable<int> MaternalDeathCount { get; set; }
        public Nullable<int> InfantDeathCount { get; set; }
        public Nullable<int> Bcgcount { get; set; }
        public Nullable<int> PentaCount { get; set; }
        public Nullable<int> OPVCount { get; set; }
        public Nullable<int> MeaslCount { get; set; }
        public Nullable<int> HBCount { get; set; }
        public Nullable<byte> BCGFlag { get; set; }
        public Nullable<byte> PentaFlag { get; set; }
        public Nullable<byte> OPVFlag { get; set; }
        public Nullable<byte> MeaslesFlag { get; set; }
        public Nullable<byte> HBFlag { get; set; }
        public Nullable<int> totalSterlization { get; set; }
        public string mthyr { get; set; }
        public Nullable<int> totalSterlizationMonth { get; set; }
        public string MName { get; set; }
        public Nullable<int> birth_boyCount { get; set; }
        public Nullable<int> birth_girlCount { get; set; }
        public double ANC3P { get; set; }
        public double InstDelP { get; set; }
        public double FullImmuP { get; set; }
        public double SterP { get; set; }
        public double IUDP { get; set; }
        public Nullable<double> maxval { get; set; }
        public Nullable<byte> pieUnittype { get; set; }
        public string HighRisk_HighBP { get; set; }
        public string HighRisk_Diabetes { get; set; }
        public string HighRisk_APH { get; set; }
        public string HighRisk_Malaria { get; set; }
        public string HighRisk_Other { get; set; }
        public string HighRisk_Anemia { get; set; }
        public string HighRisk_Age { get; set; }
        public string HighRisk_Height { get; set; }
        public string HighRisk_Delivery { get; set; }
        public string HighRisk_LieAndBreech { get; set; }
        public string HighRisk_Heart { get; set; }
        public string HighRisk_Kidney { get; set; }
    }
}
