//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspMotherlist_Result
    {
        public Nullable<int> MemberID { get; set; }
        public string BHAMASHAHID { get; set; }
        public string pctsid { get; set; }
        public int ancregid { get; set; }
        public int motherid { get; set; }
        public string villagename { get; set; }
        public string ecid { get; set; }
        public string name { get; set; }
        public string Husbname { get; set; }
        public byte Age { get; set; }
        public System.DateTime regdate { get; set; }
        public System.DateTime LMPDT { get; set; }
        public string mobileno { get; set; }
        public string AadhaarNo { get; set; }
    }
}
