//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UnitCode { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string UserContactNo { get; set; }
        public string Role { get; set; }
        public string ApplicationNos { get; set; }
        public string old2pwd { get; set; }
        public string old1pwd { get; set; }
        public byte IsDeleted { get; set; }
        public Nullable<int> unitid { get; set; }
        public Nullable<System.DateTime> PwdUpdatedDate { get; set; }
        public byte AshaRoleId { get; set; }
        public Nullable<System.DateTime> ExpireOn { get; set; }
        public byte Active { get; set; }
        public byte OJSPMRoleID { get; set; }
        public byte PctsRoleID { get; set; }
        public byte EctsRoleID { get; set; }
        public byte resetpwd { get; set; }
        public string Saltvalue { get; set; }
        public Nullable<System.DateTime> Saltcreatedon { get; set; }
        public Nullable<double> AppVersion { get; set; }
        public string AppPassword { get; set; }
        public string Imei { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int ANMAutoID { get; set; }
        public byte IsAppUser { get; set; }
        public int UserNo { get; set; }
        public byte AppRoleID { get; set; }
        public byte HRRoleID { get; set; }
        public int OfficeID { get; set; }
        public string Email { get; set; }
        public string SsoID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public int VerifiedMobile { get; set; }
        public int VerifiedEmail { get; set; }
        public int AidsRoleID { get; set; }
        public int MTPRoleID { get; set; }
        public byte DepartmentFlag { get; set; }
        public int CLMCRoleID { get; set; }
    }
}
