//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspANMASHADetailsByPCTSID_Result
    {
        public string ashaname { get; set; }
        public string ashaphone { get; set; }
        public string unitname { get; set; }
        public byte type { get; set; }
    }
}
