//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANCDetail
    {
        public int ANCRegID { get; set; }
        public byte ANCFlag { get; set; }
        public System.DateTime ANCDate { get; set; }
        public Nullable<System.DateTime> TT1 { get; set; }
        public Nullable<System.DateTime> TT2 { get; set; }
        public Nullable<System.DateTime> TTB { get; set; }
        public Nullable<System.DateTime> IFA { get; set; }
        public Nullable<double> HB { get; set; }
        public string CompL { get; set; }
        public Nullable<byte> RTI { get; set; }
        public int ashaAutoID { get; set; }
        public Nullable<double> Weight { get; set; }
        public int anganwariNo { get; set; }
        public int motherid { get; set; }
        public Nullable<int> ReferUnitID { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<int> BloodPressureS { get; set; }
        public Nullable<int> BloodPressureD { get; set; }
        public Nullable<byte> UrineA { get; set; }
        public Nullable<byte> UrineS { get; set; }
        public Nullable<int> TreatmentCode { get; set; }
        public Nullable<System.DateTime> ALBE400 { get; set; }
        public Nullable<System.DateTime> CAL500 { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public Nullable<byte> NormalLodingIronSucrose1 { get; set; }
        public Nullable<System.DateTime> IronSucrose1 { get; set; }
        public Nullable<System.DateTime> IronSucrose2 { get; set; }
        public Nullable<System.DateTime> IronSucrose3 { get; set; }
        public Nullable<System.DateTime> IronSucrose4 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte Media { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string EntryBy { get; set; }
        public Nullable<int> EntryUserNo { get; set; }
        public Nullable<int> UpdateUserNo { get; set; }
        public Nullable<byte> CovidCase { get; set; }
        public Nullable<System.DateTime> CovidFromDate { get; set; }
        public Nullable<byte> CovidForeignTrip { get; set; }
        public Nullable<byte> CovidRelativePossibility { get; set; }
        public Nullable<byte> CovidRelativePositive { get; set; }
        public Nullable<byte> CovidQuarantine { get; set; }
        public Nullable<byte> CovidIsolation { get; set; }
        public byte ANMVerify { get; set; }
        public Nullable<System.DateTime> ANMVerificationDate { get; set; }
        public Nullable<int> HepatitisBReferUnitID { get; set; }
    }
}
