//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspImmunizationListByInfantID_Result
    {
        public Nullable<int> infantid { get; set; }
        public Nullable<byte> immucode { get; set; }
        public string immudate { get; set; }
        public string immuname { get; set; }
        public Nullable<int> ashaautoid { get; set; }
        public string AshaName { get; set; }
        public Nullable<int> VillageAutoID { get; set; }
        public Nullable<int> RegUnitID { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public byte clickable { get; set; }
        public string unitcode { get; set; }
        public byte DPTFlag { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> Freeze_Immu { get; set; }
        public Nullable<int> Freeze_DBooster { get; set; }
        public Nullable<int> Freeze_DBooster2 { get; set; }
        public Nullable<byte> ANMVerify { get; set; }
        public Nullable<byte> Media { get; set; }
        public string ChildName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> Sex { get; set; }
    }
}
