//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpLog
    {
        public int Sno { get; set; }
        public int MotherID { get; set; }
        public int Infantid { get; set; }
        public string ErrorDescription { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> PushDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> ErrorID { get; set; }
        public string Status { get; set; }
        public Nullable<int> unitid { get; set; }
        public string MessageId { get; set; }
        public string ResponseStatus { get; set; }
        public byte Msgtype { get; set; }
    }
}
