//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnganwariMaster_Offline
    {
        public int AnganwariNo { get; set; }
        public string NameE { get; set; }
        public string NameH { get; set; }
        public int unitid { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte IsDeleted { get; set; }
        public Nullable<byte> RuralUrban { get; set; }
    }
}
