//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspAshaDeshbord_Result
    {
        public string unitcode { get; set; }
        public Nullable<byte> unittype { get; set; }
        public Nullable<int> AshaAutoid { get; set; }
        public Nullable<int> totalANC { get; set; }
        public Nullable<int> ANCRegTrimaster { get; set; }
        public Nullable<int> after90 { get; set; }
        public Nullable<int> TotalChildrenReg { get; set; }
        public Nullable<int> FullyImmunized { get; set; }
        public Nullable<int> PartiallyImmunized { get; set; }
        public Nullable<int> MaleCount { get; set; }
        public Nullable<int> FeMaleCount { get; set; }
        public Nullable<int> homeDelCount { get; set; }
        public Nullable<int> privateDelCount { get; set; }
        public Nullable<int> publicDelCount { get; set; }
        public Nullable<int> stllBirthCount { get; set; }
        public Nullable<int> NotImmunized { get; set; }
        public Nullable<byte> BcgFlag { get; set; }
        public Nullable<byte> pentaFlag { get; set; }
        public Nullable<byte> HBFlag { get; set; }
        public Nullable<byte> MeaslesFlag { get; set; }
        public Nullable<byte> OPVFlag { get; set; }
        public Nullable<int> BcgCount { get; set; }
        public Nullable<int> pentaCount { get; set; }
        public Nullable<int> HBCount { get; set; }
        public Nullable<int> MeaslCount { get; set; }
        public Nullable<int> OPVCount { get; set; }
    }
}
