//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspDeathData_Result
    {
        public int maternalDayCount { get; set; }
        public int maternalTwodaysCount { get; set; }
        public int maternalWeekCount { get; set; }
        public int maternalMonthCount { get; set; }
        public int maternalYearCount { get; set; }
        public int infantDayCount { get; set; }
        public int infantTwodaysCount { get; set; }
        public int infantWeekCount { get; set; }
        public int infantMonthCount { get; set; }
        public int infantYearCount { get; set; }
        public string unitname { get; set; }
        public string unitcode { get; set; }
        public string mobileno { get; set; }
        public Nullable<int> finyear { get; set; }
    }
}
