//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspMotherDataforMaternalDeath_Result
    {
        public string Name { get; set; }
        public string Husbname { get; set; }
        public string Address { get; set; }
        public byte Age { get; set; }
        public string ECID { get; set; }
        public Nullable<int> Height { get; set; }
        public int Motherid { get; set; }
        public int ancregid { get; set; }
        public System.DateTime regdate { get; set; }
        public int VillageAutoID { get; set; }
        public Nullable<int> RegUnitid { get; set; }
        public Nullable<System.DateTime> Prasav_date { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<byte> deathPlace { get; set; }
        public string Relative_Name { get; set; }
        public string MasterMobile { get; set; }
        public Nullable<byte> ReasonID { get; set; }
        public Nullable<System.DateTime> DeathReportDate { get; set; }
        public string UnitName { get; set; }
        public string deathPlaceUnitcode { get; set; }
        public Nullable<short> deathPlaceUnittype { get; set; }
        public Nullable<int> DeathUnitID { get; set; }
        public string DistrictName { get; set; }
        public string RegDistrictName { get; set; }
        public int ashaautoid { get; set; }
        public string regUntcode { get; set; }
        public string Mobileno { get; set; }
        public Nullable<int> ParentReasonId { get; set; }
        public Nullable<byte> ANMVerify { get; set; }
        public Nullable<byte> Media { get; set; }
    }
}
