//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspRecordVerificationANC_Result
    {
        public string Name { get; set; }
        public string Husbname { get; set; }
        public byte ANCFlag { get; set; }
        public System.DateTime ANCDate { get; set; }
        public string tt1 { get; set; }
        public string tt2 { get; set; }
        public string ttb { get; set; }
        public string ifa { get; set; }
        public double hb { get; set; }
        public string ALBE400 { get; set; }
        public string CAL500 { get; set; }
        public double weight { get; set; }
        public int BloodPressureS { get; set; }
        public int BloodPressureD { get; set; }
        public byte urineA { get; set; }
        public byte UrineS { get; set; }
        public string IronSucrose1 { get; set; }
        public string IronSucrose2 { get; set; }
        public string IronSucrose3 { get; set; }
        public string IronSucrose4 { get; set; }
        public string HighRisk { get; set; }
        public string ReferUnit { get; set; }
        public string VillageName { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
        public string Block { get; set; }
        public string CHCPHC { get; set; }
        public string district { get; set; }
        public int MotherID { get; set; }
        public int ANCRegID { get; set; }
    }
}
