//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class uspANCSchedule_Result
    {
        public Nullable<System.DateTime> edd { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string villname { get; set; }
        public byte bpl { get; set; }
        public byte age { get; set; }
        public string ecid { get; set; }
        public string Mobileno { get; set; }
        public string pctsid { get; set; }
        public string name { get; set; }
        public string husbname { get; set; }
        public string lmpdt { get; set; }
        public string regdate { get; set; }
        public Nullable<System.DateTime> ancdue1 { get; set; }
        public Nullable<System.DateTime> ancdue2 { get; set; }
        public Nullable<System.DateTime> ancdue3 { get; set; }
        public Nullable<System.DateTime> ancdue4 { get; set; }
        public Nullable<System.DateTime> anc1 { get; set; }
        public Nullable<System.DateTime> anc2 { get; set; }
        public Nullable<System.DateTime> anc3 { get; set; }
        public Nullable<System.DateTime> anc4 { get; set; }
        public byte DelFlag { get; set; }
    }
}
