//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AshaMaster_Offline
    {
        public string AshaName { get; set; }
        public int unitid { get; set; }
        public int ashaAutoID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte Status { get; set; }
        public Nullable<byte> type { get; set; }
    }
}
