//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PehchanBirth
    {
        public int InfantID { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> RegistrationYear { get; set; }
        public Nullable<byte> Mode { get; set; }
        public Nullable<byte> MethodFlag { get; set; }
    }
}
