//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinDetail
    {
        public string MobileNo { get; set; }
        public string Pin { get; set; }
        public System.DateTime SentDate { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<byte> trail { get; set; }
    }
}
