//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspRecordVerificationPNC_Result
    {
        public string vilaagename { get; set; }
        public string unitname { get; set; }
        public string unitcode { get; set; }
        public string CHCPHC { get; set; }
        public string Block { get; set; }
        public string district { get; set; }
        public string Name { get; set; }
        public byte PNCFlag { get; set; }
        public string compl { get; set; }
        public Nullable<byte> ppcm { get; set; }
        public Nullable<System.DateTime> pncdate { get; set; }
        public string referunit { get; set; }
    }
}
