//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    
    public partial class UspBirthCertificateList_Result
    {
        public int MotherID { get; set; }
        public string name { get; set; }
        public string Husbname { get; set; }
        public string pctsid { get; set; }
        public string Mobileno { get; set; }
        public int InfantID { get; set; }
        public string ChildName { get; set; }
        public string SexName { get; set; }
        public Nullable<byte> Sex { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string childid { get; set; }
        public int PehchanRegFlag { get; set; }
    }
}
