//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mother_Offline
    {
        public int MotherID { get; set; }
        public string ECID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public byte Age { get; set; }
        public byte Cast { get; set; }
        public byte LiveChild { get; set; }
        public string Mobileno { get; set; }
        public string Husbname { get; set; }
        public string pctsid { get; set; }
        public int ancregid { get; set; }
        public byte IsHusband { get; set; }
        public Nullable<int> Height { get; set; }
        public byte Status { get; set; }
    }
}
